---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: traefik
type: Opaque
stringData:
  email: xekwavx@gmail.com
  apiKey: eN519aIoTJB6Lu7oAQLEbJPD45muG7zHnfpXcXxU